export const GET_EARNED_COMMISION = 'GET_EARNED_COMMISION';
export const ADD_EARNED_COMMISION = 'ADD_EARNED_COMMISION';
export const EDIT_EARNED_COMMISION = 'EDIT_EARNED_COMMISION';
export const DELETE_EARNED_COMMISION = 'DELETE_EARNED_COMMISION';
export const SEARCH_EARNED_COMMISION = 'SEARCH_EARNED_COMMISION';
export const UPDATE_EARNED_COMMISION = 'UPDATE_EARNED_COMMISION';

export const GET_SALES_TRANS = 'GET_SALES_TRANS';
export const ADD_SALES_TRANS = 'ADD_SALES_TRANS';
export const EDIT_SALES_TRANS = 'EDIT_SALES_TRANS';
export const DELETE_SALES_TRANS = 'DELETE_SALES_TRANS';
export const SEARCH_SALES_TRANS = 'SEARCH_SALES_TRANS';
export const UPDATE_SALES_TRANS = 'UPDATE_SALES_TRANS';