export const GET_COMISSION = 'GET_COMISSION';
export const ADD_COMISSION = 'ADD_COMISSION';
export const EDIT_COMISSION = 'EDIT_COMISSION';
export const DELETE_COMISSION = 'DELETE_COMISSION';
export const SEARCH_COMISSION = 'SEARCH_COMISSION';
export const UPDATE_COMISSION = 'UPDATE_COMISSION';