export const GET_PRODUCT = 'GET_PRODUCT';
export const SET_PRODUCT ='SET_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

export const GET_PRICEITEM_TYPE = 'GET_PRICEITEM_TYPE';
export const ADD_PRICEITEM_TYPE = 'ADD_PRICEITEM_TYPE';
export const EDIT_PRICEITEM_TYPE = 'EDIT_PRICEITEM_TYPE';
export const DELETE_PRICEITEM_TYPE = 'DELETE_PRICEITEM_TYPE';
export const SEARCH_PRICEITEM_TYPE = 'SEARCH_PRICEITEM_TYPE';
export const UPDATE_PRICEITEM_TYPE = 'UPDATE_PRICEITEM_TYPE';