import { createAction } from 'typesafe-actions';




export const GET_PRODUCT = 'GET_PRODUCT';
export const SET_PRODUCT ='SET_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

//for sagas
export const getProduct = createAction(GET_PRODUCT)
export const setProduct = createAction(SET_PRODUCT)

export const GET_PRICEITEM_TYPE = 'GET_PRICEITEM_TYPE';
export const ADD_PRICEITEM_TYPE = 'ADD_PRICEITEM_TYPE';
export const EDIT_PRICEITEM_TYPE = 'EDIT_PRICEITEM_TYPE';
export const DELETE_PRICEITEM_TYPE = 'DELETE_PRICEITEM_TYPE';
export const SEARCH_PRICEITEM_TYPE = 'SEARCH_PRICEITEM_TYPE';
export const UPDATE_PRICEITEM_TYPE = 'UPDATE_PRICEITEM_TYPE';

export const GET_EARNED_COMMISION = 'GET_EARNED_COMMISION';
export const ADD_EARNED_COMMISION = 'ADD_EARNED_COMMISION';
export const EDIT_EARNED_COMMISION = 'EDIT_EARNED_COMMISION';
export const DELETE_EARNED_COMMISION = 'DELETE_EARNED_COMMISION';
export const SEARCH_EARNED_COMMISION = 'SEARCH_EARNED_COMMISION';
export const UPDATE_EARNED_COMMISION = 'UPDATE_EARNED_COMMISION';

export const GET_SALES_TRANS = 'GET_SALES_TRANS';
export const ADD_SALES_TRANS = 'ADD_SALES_TRANS';
export const EDIT_SALES_TRANS = 'EDIT_SALES_TRANS';
export const DELETE_SALES_TRANS = 'DELETE_SALES_TRANS';
export const SEARCH_SALES_TRANS = 'SEARCH_SALES_TRANS';
export const UPDATE_SALES_TRANS = 'UPDATE_SALES_TRANS';

export const GET_RESELLER = 'GET_RESELLER';
export const ADD_RESELLER = 'ADD_RESELLER';
export const EDIT_RESELLER = 'EDIT_RESELLER';
export const DELETE_RESELLER = 'DELETE_RESELLER';
export const UPDATE_RESELLER = 'UPDATE_RESELLER';
export const SEARCH_RESELLER = 'SEARCH_RESELLER';

export const GET_RESELLER_GROUP = 'GET_RESELLER_GROUP';
export const ADD_RESELLER_GROUP = 'ADD_RESELLER_GROUP';
export const EDIT_RESELLER_GROUP = 'EDIT_RESELLER_GROUP';
export const DELETE_RESELLER_GROUP = 'DELETE_RESELLER_GROUP';
export const SEARCH_RESELLER_GROUP = 'SEARCH_RESELLER_GROUP';
export const UPDATE_RESELLER_GROUP = 'UPDATE_RESELLER_GROUP';

export const GET_COMISSION = 'GET_COMISSION';
export const ADD_COMISSION = 'ADD_COMISSION';
export const EDIT_COMISSION = 'EDIT_COMISSION';
export const DELETE_COMISSION = 'DELETE_COMISSION';
export const SEARCH_COMISSION = 'SEARCH_COMISSION';
export const UPDATE_COMISSION = 'UPDATE_COMISSION';

