export const GET_RESELLER = 'GET_RESELLER';
export const ADD_RESELLER = 'ADD_RESELLER';
export const EDIT_RESELLER = 'EDIT_RESELLER';
export const DELETE_RESELLER = 'DELETE_RESELLER';
export const UPDATE_RESELLER = 'UPDATE_RESELLER';
export const SEARCH_RESELLER = 'SEARCH_RESELLER';

export const GET_RESELLER_GROUP = 'GET_RESELLER_GROUP';
export const ADD_RESELLER_GROUP = 'ADD_RESELLER_GROUP';
export const EDIT_RESELLER_GROUP = 'EDIT_RESELLER_GROUP';
export const DELETE_RESELLER_GROUP = 'DELETE_RESELLER_GROUP';
export const SEARCH_RESELLER_GROUP = 'SEARCH_RESELLER_GROUP';
export const UPDATE_RESELLER_GROUP = 'UPDATE_RESELLER_GROUP';